version: '3'
services:
  app:
    build:
      context: .
    volumes:
      - .:/app:cached
      - extensions:/hoge/node/.vscode-server/extensions
    network_mode: host
    tty: true
volumes:
  extensions:
